appdata/routes/web.php
Route::get('payment-history', 'PaymentListController@paymentHistory');
Route::get('payment-download', 'PaymentListController@paymentDownload');
Route::get('download-service-payment', 'PaymentListController@downloadServicePayment');
Route::get('download-profile-payment/{id}', 'PaymentListController@downloadProfilePayment');
Route::get('download-addcontroll-payment/{id}', 'PaymentListController@downloadAddControllPayment');

Route::get('add-control-payment', 'PaymentController@addControlPayment');
Route::post('add-control-payment/get-price', 'PaymentController@addControlPaymentPrice');

Route::post('add-control-payment/make', 'PaymentController@addControlMakePayment');
Route::get('add-control-payment/success', 'PaymentController@addControllPaymentSuccess');
Route::get('add-control-payment/cancel', 'PaymentController@addControllPaymentCancel');

Route::get('/services/{cat?}/{sub_cat?}/{inner_cat?}/', 'SearchServiceController@index')->name('blog');
Route::post('/services/subcategory', 'SearchServiceController@getSubCategory');
Route::get('/services/index-data', 'SearchServiceController@indexData');
Route::get('/services/pagination-data', 'SearchServiceController@paginationData');
Route::post('/vip-profile-amount', 'PaymentController@getProfileAmount')->name('getProfileAmount');
Route::post('/vip-profile-payment', 'PaymentController@profilePayment')->name('profilePayment');

Route::get('profile-payment/success', 'PaymentController@profilePaymentSuccess');
Route::get('profile-payment/cancel', 'PaymentController@profilePaymentCancel');
Route::get('index-vipdata', 'SearchServiceController@indexVipData');

Route::get('index-vip-services', 'SearchServiceController@indexVipServices');

Route::get('public-profile/{name}/{id}', 'IndexController@publicProfile')->name('publicProfile');
Route::get('public-profile/{id}/service/{title}/{s_id}', 'IndexController@publicService')->name('publicService');
Route::get('get-user-city', 'SearchServiceController@getUserCity');
Route::get('profile-list', 'SearchServiceController@profileList');
Route::post('profile-search', 'SearchServiceController@searchProfile');
Route::post('get-profile-and-service', 'SearchServiceController@profileAndService');
Route::post('active-service', 'PaymentController@activeService');

Route::post('favarite', 'IndexController@favarite');
Route::get('favarite', 'IndexController@getFavarite');

Route::get('in', 'SearchServiceController@innerCategory');

Route::post('recently_view', 'IndexController@recentlyView');
Route::get('live-zone', 'LiveZoneController@index');
Route::get('terms-and-conditions', 'IndexController@termsConditions');
Route::get('privacy-policy', 'IndexController@privacyPolicy');

Route::post('verify-sms', 'Auth\RegisterController@verifyUserSms');
Route::post('verify-email', 'Auth\RegisterController@verifyUserEmail');


// Route::get('sms-verification/{name}/{email}/{password}', 'Auth\RegisterController@vefifySms');
// Route::post('sms-verification', 'Auth\RegisterController@vefifySendedSms');
// Route::get('mail-verification/{email}/{password}', 'Auth\RegisterController@vefifyEmail');
// Route::get('send-sms', 'Auth\RegisterController@sendSms');

Route::post('user/live-zone/upload-image', 'LiveZoneController@UploadImage');
Route::post('user/live-zone/upload-youtube-video', 'LiveZoneController@UploadYourtubeVideo');
Route::post('user/live-zone/save-livezone', 'LiveZoneController@saveLiveZone');
Route::post('user/live-zone/firstlike', 'LiveZoneController@saveFirstLike');
Route::post('user/live-zone/first-comment', 'LiveZoneController@saveFirstComment');
Route::post('user/live-zone/first-comment-popup', 'LiveZoneController@saveFirstCommentPopup');
Route::post('user/live-zone/comment-like', 'LiveZoneController@commentLike');
Route::post('user/live-zone/sub-comment-like', 'LiveZoneController@subCommentLike');
Route::post('user/live-zone/sub-comment', 'LiveZoneController@saveSubComment');
Route::post('user/live-zone/sub-comment-popup', 'LiveZoneController@saveSubCommentPopup');
Route::post('user/live-zone/sub-comment-reply', 'LiveZoneController@saveSubCommentReply');
Route::post('user/live-zone/sub-comment-reply-popup', 'LiveZoneController@saveSubCommentReplyPopup');
Route::post('user/live-zone/see-more-comment', 'LiveZoneController@seeMoreComment');
Route::post('user/live-zone/see-more-comment-popup', 'LiveZoneController@seeMoreCommentPopup');
Route::post('user/live-zone/see-more-sub-comment', 'LiveZoneController@seeMoreSubComment');
Route::post('user/live-zone/see-more-sub-comment-popup', 'LiveZoneController@seeMoreSubCommentPopup');
Route::post('user/service/save-service-comment', 'LiveZoneController@saveServiceComment');
Route::post('user/service/save-service-comment-replay', 'LiveZoneController@saveServiceCommentReplay');
Route::post('user/service/load-more-service-comment', 'LiveZoneController@loadMoreServiceComment');
Route::post('user/live-zone/open-popup', 'LiveZoneController@openPopUp');
Route::get('user/live-zone/pagination', 'LiveZoneController@getPagiantionData');
Route::post('see-more-gallery', 'IndexController@seeMoreGallery');

Route::get('test-sms', 'Auth\RegisterController@testSms');


//end rasel route




Route::namespace('Auth')->group(function () {
	Route::post('registration', 'RegisterController@registration')->name('registration');
});
Route::group(['prefix' => 'user'], function () {

	Route::name('user.')->group(function () {

		Route::post('get-service-gallery-tab', 'IndexController@getServiceGlryTab')->name('getServiceGlryTab');
		Route::namespace('Auth')->group(function () {

			// Route::get('login', 'LoginController@showLoginForm')->name('login');	
			Route::post('login', 'LoginController@login')->name('login.submit');
			Route::post('logout', 'LoginController@logout')->name('logout');
		});
		Route::namespace('User')->group(function () {
			// profile
			Route::post('add-live-zone', 'ProfileController@addLiveZone');
			Route::post('edit-live-zone', 'ProfileController@editLiveZone');
			Route::post('update-live-zone', 'ProfileController@liveZoneUpdate');
			Route::post('delete-live-zone', 'ProfileController@liveZoneDelete');
			Route::post('add-comment', 'CommentController@addComment');
			Route::post('main-comment-replay', 'CommentController@replayMainComment');
			Route::post('send-email-after-login', 'ProfileController@sendUserVcode');
			Route::post('verify-email-after-login', 'ProfileController@verifyUserEmail');


			Route::get('profile', 'ProfileController@index')->name('profile');
			Route::get('booking-list', 'ProfileController@bookingList')->name('bookingList');
			Route::get('services/{service}/types/{type}/bookings/{booking}/cancle', 'ProfileController@cancledBooking');
			Route::post('cancle-booking', 'ProfileController@cancledBook');
			Route::get('calendar/create', 'CalendarController@index')->name('calendar');
			Route::post('calendar/getsession', 'CalendarController@getSession')->name('getSession');
			Route::post('gallery-file-upload', 'ProfileController@galleryFileUp')->name('galleryFileUp');
			Route::post('gallery-file-remove', 'ProfileController@galleryRemover')->name('galleryRemover');
			Route::post('update-user-picture', 'ProfileController@upPrPic');
			Route::post('process-single-tmp-image', 'ProfileController@setProfilePic');
			Route::post('single-tmp-img-remove', 'ProfileController@removeProfilePic');
			Route::post('update-business-hour', 'ProfileController@updateBusinessHour');

			Route::post('cover-image-upload', 'ProfileController@coverImgUpload');
			Route::post('update-cover-img', 'ProfileController@coverImgUpdate');
			Route::post('user-cover-remove', 'ProfileController@userCoverRemover')->name('userCoverRemover');

			Route::post('get-profile-information', 'ProfileController@getProfileInfo');
			Route::post('insert-profile-information', 'ProfileController@insertProfileInfo');
			Route::post('service-address', 'ServicesController@saveServiceAddress')->name('saveServiceAddress');
			Route::get('my-service/{title}/{id}', 'ServicesController@index')->name('myService');
			Route::get('add-my-service', 'ServicesController@add')->name('addMyService');
			Route::post('change-service-details', 'ServicesController@changeServiceDetails')->name('changeServiceDetails');
			Route::post('service-tmp-img', 'ServicesController@serviceTmpImg')->name('serviceTmpImg');
			Route::post('update-service-image', 'ServicesController@updateServiceImg')->name('updateServiceImg');
			Route::post('service-tmp-img-remove', 'ServicesController@serviceTmpImgRemove')->name('serviceTmpImgRemove');
			Route::post('change-service-sub-category', 'ServicesController@changeServiceSubCategory')->name('changeServiceSubCategory');
			Route::post('change-service-inner-category', 'ServicesController@changeServiceInnerCategory')->name('changeServiceInnerCategory');
			Route::post('save-service-category', 'ServicesController@saveServiceCategory')->name('saveServiceCategory');
			Route::post('save-service-gallery-tab', 'ServicesController@saveServiceGlryTab')->name('saveServiceGlryTab');
			Route::post('del-service-gallery-tab', 'ServicesController@delServiceGlryTab')->name('delServiceGlryTab');
			Route::post('update-service-gallery-tab', 'ServicesController@updateServiceGlryTab')->name('updateServiceGlryTab');
			Route::post('add-service-gallery-image', 'ServicesController@addServiceGalleryImg')->name('addServiceGalleryImg');
			Route::post('service-gallery-image-upload', 'ServicesController@serviceGalleryImgUpload')->name('serviceGalleryImgUpload');
			Route::post('service-gallery-image-delete', 'ServicesController@serviceGalleryImgDelete')->name('serviceGalleryImgDelete');
			Route::post('service-gallery-tmp-image-remove', 'ServicesController@serviceGalleryTmpImgRemove')->name('serviceGalleryTmpImgRemove');

			// calendar
			// Route::get('calendar-list', 'CalendarController@calnedarList')->name('calnedarList');
		});
	});
});
Route::get('404-not-found', 'IndexController@errors')->name('404');

appdata/resources/views/inc/footer.blade.php
<section class="footer-section">
	<div class="max-fix-width">
		<div class="row mar-0">
			<div class="col-12 col-lg-4">
				<div class="d-con">
					<div class="f-logo"><img src="{{asset('assets/img/logo1.png')}}"></div>
					<div class="f-txt">@lang('lang.footer_text')</div>
					<div class="f-card">
						<img src="{{ asset('assets/img/pay-1.png') }}" alt="Left Arrow Key">
						<img src="{{ asset('assets/img/pay-2.png') }}" alt="Left Arrow Key">
						<img src="{{ asset('assets/img/pay-3.png') }}" alt="Left Arrow Key">
						<img src="{{ asset('assets/img/pay-4.png') }}" alt="Left Arrow Key">
						<img src="{{ asset('assets/img/pay-5.png') }}" alt="Left Arrow Key">
					</div>
				</div>
			</div>
			<div class="col-12 col-lg-5">
				<div class="f-menu">
					<div class="f-menu1">
						<h1>@lang('lang.navigation')</h1>
						<ul>
							<li><a href="#">@lang('lang.home')</a></li>
							<li><a href="#">@lang('lang.pages')</a></li>
							<li><a href="#">@lang('lang.models')</a></li>
							<li><a href="#">@lang('lang.appointment')</a></li>
							<li><a href="#">@lang('lang.faq')</a></li>
							<li><a href="#">@lang('lang.contact')Cont</a></li>
						</ul>
					</div>
					<div class="f-menu1">
						<h1>@lang('lang.navigation')</h1>
						<ul>
							<li><a href="#">@lang('lang.home')</a></li>
							<li><a href="#">@lang('lang.pages')</a></li>
							<li><a href="#">@lang('lang.models')</a></li>
							<li><a href="#">@lang('lang.appointment')</a></li>
							<li><a href="#">@lang('lang.faq')</a></li>
							<li><a href="#">@lang('lang.contact')</a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="col-12 col-lg-3 p-0">
				<div id="carouselExampleControls1" class="carousel slide" data-interval="false" data-ride="carousel">
					<div class="carousel-inner">
						<div class="carousel-item active">
							<div class="footer-adv">
								<h1>@lang('lang.ypatingi_pasiulymai')</h1>
								<div class="footer-adv-img">
									<img src="{{asset('assets/img/services/demo.jpg')}}">
								</div>
							</div>
						</div>
						<div class="carousel-item ">
							<div class="footer-adv">
								<h1>@lang('lang.ypatingi_pasiulymai')</h1>
								<div class="footer-adv-img">
									<img src="{{asset('assets/img/services/demo.jpg')}}">
								</div>
							</div>
						</div>
						<div class="carousel-item ">
							<div class="footer-adv">
								<h1>@lang('lang.ypatingi_pasiulymai')</h1>
								<div class="footer-adv-img">
									<img src="{{asset('assets/img/services/demo.jpg')}}">
								</div>
							</div>
						</div>
					</div>
					<a class="carousel-control-prev" href="#carouselExampleControls1" role="button" data-slide="prev">
						<span><i class="fas fa-chevron-left"></i></span>
						<span class="sr-only">@lang('lang.previous')</span>
					</a>
					<a class="carousel-control-next" href="#carouselExampleControls1" role="button" data-slide="next">
						<span><i class="fas fa-chevron-right"></i></span>
						<span class="sr-only">@lang('lang.next')</span>
					</a>
				</div>

				<div class="adv-btn">
					<button class="btn ad-btn1">@lang('lang.prenumeruoti_naujienas')</button>
					<button class="btn ad-btn2">@lang('lang.susisiekti')</button>
				</div>
			</div>
		</div>
		<div class="copy-txt">
			<a href="{{url('terms-and-conditions')}}">@lang('lang.terms_and_conditions')</a>
			|
			<a href="{{url('privacy-policy')}}">Privacy Policy</a>
			@lang('lang.reserved')
		</div>
	</div>
</section>
<div class="mbl-icon-menu d-flex d-lg-none">
	<a href="{{url('/')}}">
		<div class="menu-item"><img src="{{ asset('assets/img/home.png') }}" alt="menu-icon"></div>
	</a>
	<a href="#">
		<div class="menu-item"><img src="{{ asset('assets/img/offers.png') }}" alt="menu-icon"></div>
	</a>
	<a href="{{url('profile-list')}}">
		<div class="menu-item"><img src="{{ asset('assets/img/users.png') }}" alt="menu-icon"></div>
	</a>
	<a href="{{url('/user/calendar/create')}}" class="auth-check <?= (Auth::guard('web')->check()) ? '' : 'd-none'; ?>">
		<div class="menu-item">
			<img src="{{ asset('assets/img/sell_service.png') }}" alt="menu-icon">
			<span class="count-l">2</span>
		</div>
	</a>
	<a href="{{url('/user/booking-list')}}" class="auth-check <?= (Auth::guard('web')->check()) ? '' : 'd-none'; ?>">
		<div class="menu-item">
			<img src="{{ asset('assets/img/buy_service.png') }}" alt="menu-icon">
			<span class="count-l">2</span>
		</div>
	</a>
</div>

appdata/resources/views/inc/header-filter-new.blade.php
<input type="hidden" name="price" id="price" value="@if(Session::has('h_price')) {{Session::get('h_price')}} @else 0,100 @endif">
<input type="hidden" name="distance" id="distance" value="@if(Session::has('h_distance')) {{Session::get('h_distance')}} @else 100 @endif">

<section class="header-filter">
	<div class="form-section form-sh">
		<div class="form-all">
			<div class="row mar-0">
				<div class="col-12 col-md-6 col-lg-2 p-0">
					<div class="form-group p-0 m-0 slct-adr">
						<span class="adr-icon"><i class="fa fa-map-marker-alt"></i></span>
						<input type="text" class="form-control" id="index-address" aria-describedby="emailHelp" placeholder="Type address" autocomplete="off" value="{{Session::get('address')}}">
						<span class="select-arr"><i class="fas fa-plus"></i></span>
					</div>
				</div>
				<div class="col-12 col-md-6 col-lg-2">
					<div class="form-group p-0 m-0 slct-adr">
						<span><label class="ctm-container">@lang('lang.paslaugos')
							<input type="checkbox" class="personal" name="personal" value="1" @if(Session::has('h_personal')) @if(Session::get('h_personal') == 1) checked @endif @else checked @endif>
							<span class="checkmark"></span>
						</label></span>
						<span><label class="ctm-container">@lang('lang.meistrai')
							<input type="checkbox" class="salons" name="salons" value="1" @if(Session::has('h_salons')) @if(Session::get('h_salons') == 1) checked @endif @else checked @endif>
							<span class="checkmark"></span>
						</label></span>
					</div>
				</div>
				<div class="col-12 col-md-4 col-lg-3 pr-0">
					<div class="form-group p-0 m-0 slct-adr">
						<span class="adr-icon">@lang('lang.km')</span>
						<div class="range-mul range-mul1" id="hd1" onclick="getServices(1)"></div>
					</div>
				</div>
				<div class="col-12 col-md-6 col-lg-4 pr-0">
					<div class="form-group p-0 m-0 slct-adr">
						<span class="adr-icon">@lang('lang.c')</span>
						<span class="adr-min">@lang('lang.min')</span>
						<div class="range-mul" id="hd2" onclick="getServices(2)"></div>
						<span class="adr-max">@lang('lang.max')</span>
					</div>
				</div>
				<div class="col-12 col-md-2 col-lg-1 pr-0">
					<div class="form-group p-0 m-0 slct-adr">
						<a href="{{url('reset-session-data')}}"><div class="ran-tlt">@lang('lang.anuliuoti')</div></a>
					</div>
				</div>
			</div>
		</div>
	</div> 
	<div class="line-h">
		<!-- <span class="line-icon"><i class="fas fa-chevron-down"></i></span> -->
	</div>
</section>

appdata/resources/views/inc/header-filter-new2.blade.php
<input type="hidden" name="category" id="category" value="{{$item['category']}}" class="s_category">
<input type="hidden" name="sub_category" id="sub_category" value="{{$item['sub_category']}}" class="s_sub_category">
<input type="hidden" name="inner_category" id="inner_category" value="{{@$item['inner_category']}}" class="s_inner_category">
<input type="hidden" name="price" id="price" value="{{$item['price']}}">
<input type="hidden" name="distance" id="distance" value="{{$item['distance']}}">
<section class="header-filter">
	<div class="form-section form-sh">
		<div class="form-all">
			<div class="row mar-0">
				<div class="col-12 col-md-6 col-lg-2 p-0">
					<div class="form-group p-0 m-0 slct-adr">
						<span class="adr-icon"><i class="fa fa-map-marker-alt"></i></span>
						<input type="text" class="form-control" id="service-address" aria-describedby="emailHelp" placeholder="Type address" autocomplete="off" value="@if(Session::has('address')){{Session::get('address')}}@else {{ 'Rasel' }} @endif">
						<span class="select-arr"><i class="fas fa-plus"></i></span>
					</div>
				</div>
				<div class="col-12 col-md-6 col-lg-2">
					<div class="form-group p-0 m-0 slct-adr">
						<span><label class="ctm-container">@lang('lang.paslaugos')
							<input type="checkbox" class="personal" name="personal" value="1" @if(@$item['personal'] ==1) checked @endif>
							<span class="checkmark"></span>
						</label></span>
						<span><label class="ctm-container">@lang('lang.meistrai')
							<input type="checkbox" class="salons" name="salons" value="1" @if(@$item['salons'] ==1) checked @endif>
							<span class="checkmark"></span>
						</label></span>
					</div>
				</div>
				<div class="col-12 col-md-4 col-lg-3 pr-0">
					<div class="form-group p-0 m-0 slct-adr">
						<span class="adr-icon">@lang('lang.km')</span>
						<!-- <span class="adr-min">@lang('lang.min')</span> -->
						<div class="range-mul range-mul1" id="hd1" onclick="getServices(1)"></div>
						<!-- <span class="adr-max">@lang('lang.max')</span> -->
					</div>
				</div>
				<div class="col-12 col-md-6 col-lg-4 pr-0">
					<div class="form-group p-0 m-0 slct-adr">
						<span class="adr-icon">@lang('lang.c')</span>
						<span class="adr-min">@lang('lang.min')</span>
						<div class="range-mul" id="hd2" onclick="getServices(2)"></div>
						<span class="adr-max">@lang('lang.max')</span>
					</div>
				</div>
				<div class="col-12 col-md-2 col-lg-1 pr-0">
					<div class="form-group p-0 m-0 slct-adr">
						<div class="ran-tlt" onclick="resetAll()">@lang('lang.anuliuoti')</div>
					</div>
				</div>
			</div>
		</div>
	</div> 
	<div class="line-h">
		<!-- <span class="line-icon"><i class="fas fa-chevron-down"></i></span> -->
	</div>
</section>

appdata/resources/views/inc/login.blade.php
<!-- Modal -->
<div class="modal fade" id="loginPopUp" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-body">
				<section class="header-filter mar-0">
					<div class="form-section">
						<div class="form-all">
							<div class="row mar-0">
								<div class="col-12 pad-0">
									<h1 class="title">@lang('lang.login')</h1>
								</div>
								<div class="col-12 pad-0">
									<div class="form-group">
										<a href="{{url('user/redirect',['facebook'])}}">
											<button class="loginBtn loginBtn--facebook" type="button">
												@lang('lang.login_with_facebook')
											</button>
										</a>
										<a href="{{url('user/redirect',['google'])}}">
											<button class="loginBtn loginBtn--google" type="button">
												@lang('lang.login_with_google')
											</button>
										</a>
									</div>
								</div>
								<form action="{{ route('user.login.submit') }}" method="post" class="wth-100-p" onsubmit="validateUserLogin(event);">
									@csrf
									<div class="col-12 pad-0">
										<div class="form-group">
											<label for="LEmail">@lang('lang.email') <span class="c-red">*</span></label>
											<input type="text" id="LEmail" class="form-control" placeholder="Email or Phone" aria-label="Email" name="email">
										</div>
									</div>
									<div class="col-12 pad-0">
										<div class="form-group">
											<label for="LPassword">@lang('lang.password')<span class="c-red">*</span></label>
											<input type="password" id="LPassword" class="form-control" placeholder="Password" aria-label="Password" name="password">
										</div>
									</div>
									<div class="col-12 pad-0">
										<h5 class="c-red p-l-10 login-error d-none"></h5>
									</div>
									<div class="col-12 pad-0">
										<div class="form-group">
											<button class="btn btn-ctm">@lang('lang.login')</button>
											<button class="btn r-btn" type="button" data-toggle="modal" data-target="#registrationPopUp" onclick="$('#loginPopUp').modal('hide')">
												@lang('lang.register')
											</button>
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>
				</section>
			</div>
		</div>
	</div>
</div>
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v5.0"></script>

appdata/resources/views/inc/switch-acnt.blade.php
@if(Auth::guard('web')->check())
<div class="switch-acnt-box">
    <div class="acnt-list">
        <a href="{{url('/user/profile')}}">@lang('lang.profile')</a>
    </div>
    <div class="acnt-list">
        <a href="{{url('/user/calendar/create')}}">@lang('lang.create_calendar')</a>
    </div>
    <div class="acnt-list">
        <a href="{{url('payment-history')}}">@lang('lang.payment_history')</a>
    </div>
    <div class="acnt-list">
        <a href="{{url('/user/booking-list')}}">@lang('lang.booking_list')</a>
    </div>
    <div class="acnt-list">
        <a href="{{url('payment-list')}}">@lang('lang.service_payment')</a>
    </div>
    <div class="acnt-list">
        <a href="{{url('add-control-payment')}}">@lang('lang.remove_adds')</a>
    </div>
    <div class="acnt-list">
        <div class="lan-flag">
            <div class="en-flag {{ (config('app.locale')=='en' ) ? '' : 'd-none' }}">
                <img src="{{ asset('assets/lan/en.png') }}" alt="lan flag" />
            </div>
            <div class="lt-flag {{ (config('app.locale')=='lt' ) ? '' : 'd-none' }}">
                <img src="{{ asset('assets/lan/lt.png') }}" alt="lan flag" />
            </div>
            <div class="rs-flag {{ (config('app.locale')=='rs' ) ? '' : 'd-none' }}">
                <img src="{{ asset('assets/lan/rs.png') }}" alt="lan flag" />
            </div>
            <div class="lan-pop-up d-none">
                <div class="lan-name" onclick="changeLanguage('en')">@lang('lang.english')</div>
                <div class="lan-name" onclick="changeLanguage('lt')">@lang('lang.lithuania')</div>
                <div class="lan-name" onclick="changeLanguage('rs')">@lang('lang.rashiya')</div>
            </div>
        </div>
    </div>
    <div class="m-logout">
        <a href="{{ route('user.logout') }}" onclick="event.preventDefault();
					document.getElementById('logout-form').submit();">
            <button class="btn p-btn l-btn">@lang('lang.log_out')</button>
            <form id="logout-form" action="{{ route('user.logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
        </a>
    </div>
</div>
@else
<div class="lg-btn">
    <!-- <span><i class="fas fa-chevron-right"></i> </span> -->
    <!-- <span><button class="btn p-btn r-btn" data-toggle="modal" data-target="#registrationPopUp">@lang('lang.register')</button> </span> -->
    <div class="lan-flag d-none d-lg-block">
        <div class="en-flag {{ (config('app.locale')=='en' ) ? '' : 'd-none' }}">
            <img src="{{ asset('assets/lan/en.png') }}" alt="lan flag" />
        </div>
        <div class="lt-flag {{ (config('app.locale')=='lt' ) ? '' : 'd-none' }}">
            <img src="{{ asset('assets/lan/lt.png') }}" alt="lan flag" />
        </div>
        <div class="rs-flag {{ (config('app.locale')=='rs' ) ? '' : 'd-none' }}">
            <img src="{{ asset('assets/lan/rs.png') }}" alt="lan flag" />
        </div>
        <div class="lan-pop-up d-none">
            <div class="lan-name" onclick="changeLanguage('en')">@lang('lang.english')</div>
            <div class="lan-name" onclick="changeLanguage('lt')">@lang('lang.lithuania')</div>
            <div class="lan-name" onclick="changeLanguage('rs')">@lang('lang.rashiya')</div>
        </div>
    </div>
    <span><button class="btn p-btn l-btn" data-toggle="modal" data-target="#loginPopUp">@lang('lang.log_in')</button> </span>
</div>
@endif

appdata/resources/views/inc/verify-email.blade.php
<!-- Modal -->

<div class="modal fade" id="verifyEmail" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Verify Email</h5>
      </div>
      <div class="modal-body">
        <form id="v-e-send" method="post" action="{{url('user/send-email-after-login')}}">
          @csrf
          <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <input type="email" class="form-control verifyEmail" id="v-e-email-address" aria-describedby="emailHelp" required>
            <small id="emailHelp1" class="form-text text-muted"></small>
          </div>
          <button type="submit" class="btn btn-primary">Verify</button>
        </form>
        <form id="v-e-code">
          <div class="form-group">
            <label for="exampleInputEmail1">Verification Code</label>
            <input type="text" class="form-control verifyEmail" id="v-e-v-code" aria-describedby="emailHelp" required>
            <small id="emailHelp2" class="form-text text-muted"></small>
          </div>
          <button type="submit" class="btn btn-primary">Verify</button>
        </form>
      </div>
    </div>
  </div>
</div>