appdata/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index')->name('index');
Route::get('localization/{locale}', 'LocalizationController@index');


Route::get('/service/{page_title?}/{id}', 'IndexController@aboutM')->name('aboutM');

Route::get('/user-profile', 'IndexController@userProfile')->name('userProfile');

//Rasel Route


Route::post('set-visitor-location', 'IndexController@setVisitorLocation');
Route::post('reset-visitor-location', 'IndexController@resetVisitorLocation');
Route::post('set-search-history', 'IndexController@setSearchHistory');
Route::get('reset-session-data', 'IndexController@resetSession');

Route::post('search-service-title', 'IndexController@searchServiceTitle');
Route::get('/select-plan/{id}', 'IndexController@selectPlan')->name('selectPlan');
Route::post('/select-plan/amount-calculation', 'PaymentController@amountCalculation');
Route::post('/select-plan/amount-with-star', 'PaymentController@starAmount');
Route::post('/select-plan/payment', 'PaymentController@payment');
Route::get('/stripe/success', 'PaymentController@paymentSuccess');
Route::get('/stripe/cancel', 'PaymentController@stripeCancel');
Route::get('/paysera/success', 'PaymentController@paymentSuccess');
Route::get('/paysera/cancel', 'PaymentController@payseraCancel');
Route::get('/paysera/callback', 'PaymentController@payseraCallback');
Route::get('payment-list', 'PaymentListController@index');
Route::get('payment-history', 'PaymentListController@paymentHistory');
Route::get('payment-download', 'PaymentListController@paymentDownload');
Route::get('download-service-payment', 'PaymentListController@downloadServicePayment');
Route::get('download-profile-payment/{id}', 'PaymentListController@downloadProfilePayment');
Route::get('download-addcontroll-payment/{id}', 'PaymentListController@downloadAddControllPayment');

Route::get('add-control-payment', 'PaymentController@addControlPayment');
Route::post('add-control-payment/get-price', 'PaymentController@addControlPaymentPrice');

Route::post('add-control-payment/make', 'PaymentController@addControlMakePayment');
Route::get('add-control-payment/success', 'PaymentController@addControllPaymentSuccess');
Route::get('add-control-payment/cancel', 'PaymentController@addControllPaymentCancel');

Route::get('/services/{cat?}/{sub_cat?}/{inner_cat?}/', 'SearchServiceController@index')->name('blog');
Route::post('/services/subcategory', 'SearchServiceController@getSubCategory');
Route::get('/services/index-data', 'SearchServiceController@indexData');
Route::get('/services/pagination-data', 'SearchServiceController@paginationData');
Route::post('/vip-profile-amount', 'PaymentController@getProfileAmount')->name('getProfileAmount');
Route::post('/vip-profile-payment', 'PaymentController@profilePayment')->name('profilePayment');

Route::get('profile-payment/success', 'PaymentController@profilePaymentSuccess');
Route::get('profile-payment/cancel', 'PaymentController@profilePaymentCancel');
Route::get('index-vipdata', 'SearchServiceController@indexVipData');

Route::get('index-vip-services', 'SearchServiceController@indexVipServices');

Route::get('public-profile/{name}/{id}', 'IndexController@publicProfile')->name('publicProfile');
Route::get('public-profile/{id}/service/{title}/{s_id}', 'IndexController@publicService')->name('publicService');
Route::get('get-user-city', 'SearchServiceController@getUserCity');
Route::get('profile-list', 'SearchServiceController@profileList');
Route::post('profile-search', 'SearchServiceController@searchProfile');
Route::post('get-profile-and-service', 'SearchServiceController@profileAndService');
Route::post('active-service', 'PaymentController@activeService');

Route::post('favarite', 'IndexController@favarite');
Route::get('favarite', 'IndexController@getFavarite');

Route::get('in', 'SearchServiceController@innerCategory');

Route::post('recently_view', 'IndexController@recentlyView');
Route::get('live-zone', 'LiveZoneController@index');
Route::get('terms-and-conditions', 'IndexController@termsConditions');
Route::get('privacy-policy', 'IndexController@privacyPolicy');

Route::post('verify-sms', 'Auth\RegisterController@verifyUserSms');
Route::post('verify-email', 'Auth\RegisterController@verifyUserEmail');


// Route::get('sms-verification/{name}/{email}/{password}', 'Auth\RegisterController@vefifySms');
// Route::post('sms-verification', 'Auth\RegisterController@vefifySendedSms');
// Route::get('mail-verification/{email}/{password}', 'Auth\RegisterController@vefifyEmail');
// Route::get('send-sms', 'Auth\RegisterController@sendSms');

Route::post('user/live-zone/upload-image', 'LiveZoneController@UploadImage');
Route::post('user/live-zone/upload-youtube-video', 'LiveZoneController@UploadYourtubeVideo');
Route::post('user/live-zone/save-livezone', 'LiveZoneController@saveLiveZone');
Route::post('user/live-zone/firstlike', 'LiveZoneController@saveFirstLike');
Route::post('user/live-zone/first-comment', 'LiveZoneController@saveFirstComment');
Route::post('user/live-zone/first-comment-popup', 'LiveZoneController@saveFirstCommentPopup');
Route::post('user/live-zone/comment-like', 'LiveZoneController@commentLike');
Route::post('user/live-zone/sub-comment-like', 'LiveZoneController@subCommentLike');
Route::post('user/live-zone/sub-comment', 'LiveZoneController@saveSubComment');
Route::post('user/live-zone/sub-comment-popup', 'LiveZoneController@saveSubCommentPopup');
Route::post('user/live-zone/sub-comment-reply', 'LiveZoneController@saveSubCommentReply');
Route::post('user/live-zone/sub-comment-reply-popup', 'LiveZoneController@saveSubCommentReplyPopup');
Route::post('user/live-zone/see-more-comment', 'LiveZoneController@seeMoreComment');
Route::post('user/live-zone/see-more-comment-popup', 'LiveZoneController@seeMoreCommentPopup');
Route::post('user/live-zone/see-more-sub-comment', 'LiveZoneController@seeMoreSubComment');
Route::post('user/live-zone/see-more-sub-comment-popup', 'LiveZoneController@seeMoreSubCommentPopup');
Route::post('user/service/save-service-comment', 'LiveZoneController@saveServiceComment');
Route::post('user/service/save-service-comment-replay', 'LiveZoneController@saveServiceCommentReplay');
Route::post('user/service/load-more-service-comment', 'LiveZoneController@loadMoreServiceComment');
Route::post('user/live-zone/open-popup', 'LiveZoneController@openPopUp');
Route::get('user/live-zone/pagination', 'LiveZoneController@getPagiantionData');
Route::post('see-more-gallery', 'IndexController@seeMoreGallery');

Route::get('test-sms', 'Auth\RegisterController@testSms');


//end rasel route




Route::namespace('Auth')->group(function () {
	Route::post('registration', 'RegisterController@registration')->name('registration');
});
Route::group(['prefix' => 'user'], function () {

	Route::name('user.')->group(function () {

		Route::post('get-service-gallery-tab', 'IndexController@getServiceGlryTab')->name('getServiceGlryTab');
		Route::namespace('Auth')->group(function () {

			// Route::get('login', 'LoginController@showLoginForm')->name('login');	
			Route::post('login', 'LoginController@login')->name('login.submit');
			Route::post('logout', 'LoginController@logout')->name('logout');
		});
		Route::namespace('User')->group(function () {
			// profile
			Route::post('add-live-zone', 'ProfileController@addLiveZone');
			Route::post('edit-live-zone', 'ProfileController@editLiveZone');
			Route::post('update-live-zone', 'ProfileController@liveZoneUpdate');
			Route::post('delete-live-zone', 'ProfileController@liveZoneDelete');
			Route::post('add-comment', 'CommentController@addComment');
			Route::post('main-comment-replay', 'CommentController@replayMainComment');
			Route::post('send-email-after-login', 'ProfileController@sendUserVcode');
			Route::post('verify-email-after-login', 'ProfileController@verifyUserEmail');


			Route::get('profile', 'ProfileController@index')->name('profile');
			Route::get('booking-list', 'ProfileController@bookingList')->name('bookingList');
			Route::get('services/{service}/types/{type}/bookings/{booking}/cancle', 'ProfileController@cancledBooking');
			Route::post('cancle-booking', 'ProfileController@cancledBook');
			Route::get('calendar/create', 'CalendarController@index')->name('calendar');
			Route::post('calendar/getsession', 'CalendarController@getSession')->name('getSession');
			Route::post('gallery-file-upload', 'ProfileController@galleryFileUp')->name('galleryFileUp');
			Route::post('gallery-file-remove', 'ProfileController@galleryRemover')->name('galleryRemover');
			Route::post('update-user-picture', 'ProfileController@upPrPic');
			Route::post('process-single-tmp-image', 'ProfileController@setProfilePic');
			Route::post('single-tmp-img-remove', 'ProfileController@removeProfilePic');
			Route::post('update-business-hour', 'ProfileController@updateBusinessHour');

			Route::post('cover-image-upload', 'ProfileController@coverImgUpload');
			Route::post('update-cover-img', 'ProfileController@coverImgUpdate');
			Route::post('user-cover-remove', 'ProfileController@userCoverRemover')->name('userCoverRemover');

			Route::post('get-profile-information', 'ProfileController@getProfileInfo');
			Route::post('insert-profile-information', 'ProfileController@insertProfileInfo');
			Route::post('service-address', 'ServicesController@saveServiceAddress')->name('saveServiceAddress');
			Route::get('my-service/{title}/{id}', 'ServicesController@index')->name('myService');
			Route::get('add-my-service', 'ServicesController@add')->name('addMyService');

appdata/resources/views/pages/booking-list.blade.php
@extends('layout.app')
@section('style')
<link rel="stylesheet" type="text/css" href="{{ asset('assets/DataTables/css/jquery.dataTables.min.css') }}">
<style type="text/css">
    .gm-style-iw {
        max-width: 300px !important;
        max-height: 300px !important;
    }

    .gm-style-iw-d {
        max-width: 300px !important;
        max-height: 300px !important;
    }
</style>
@endsection
@section('content')
@include('inc.header-filter-new')
<section class="about-section">
    <div class="max-fix-width">
        <div class="link-menu">
            <span class="arrow-l"><i class="fas fa-arrow-left"></i></span>
            <span><a href="#">@lang('lang.booking_List')</a></span>
        </div>
        <div class="row mar-0">
            <div class="col-12 col-lg-8">
                <div class="booking-list-area">
                    <div class="table-responsive rendar-booking-data">
                        @include('pages.booking-list-data')
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-4">
                <div class="social-icon">
                    <ul>
                        <li class="{{ (Auth::user()->facebook) ? '' : 'd-none' }}"><a class="fb" href="{{ Auth::user()->facebook }}" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
                        <li class="{{ (Auth::user()->twitter) ? '' : 'd-none' }}"><a class="tw" href="{{ Auth::user()->twitter }}" target="_blank"><i class="fab fa-twitter"></i></a></li>
                        <li class="{{ (Auth::user()->gmail) ? '' : 'd-none' }}"><a class="go" href="{{ Auth::user()->gmail }}" target="_blank"><i class="fab fa-goodreads-g"></i></a></li>
                        <li class="{{ (Auth::user()->linkedin) ? '' : 'd-none' }}"><a class="lin" href="{{ Auth::user()->linkedin }}" target="_blank"><i class="fab fa-linkedin-in"></i></a></li>
                        <li class="{{ (Auth::user()->pinterest) ? '' : 'd-none' }}"><a class="pin" href="{{ Auth::user()->pinterest }}" target="_blank"><i class="fab fa-pinterest-p"></i></a></li>
                    </ul>
                </div>
                <div class="pro-box">
                    <div class="row">
                        <div class="col-12">
                            <div class="pro-cnt">
                                <div class="pro-name">{{ Auth::user()->name }} {{ Auth::user()->surname }} {{ (Auth::user()->nickname) ? '(' . Auth::user()->nickname . ')' : '' }}</div>
                                <div class="pro-email"><i class="fa fa-envelope"></i> {{ Auth::user()->email }}</div>
                                <div class="pro-phn"><i class="fas fa-mobile-alt"></i>{{ Auth::user()->phone}}</div>
                                <div class="pro-btn">
                                    <a href="{{ route('user.profile') }}"><button class="p-btn btn">@lang('lang.profle')</button></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="side-blog">
                    <section class="blog-section">
                        <div class="pop-master">
                            <h1>@lang('lang.populer_masters')</h1>
                        </div>
                        <div class="blog">
                            <div class="blog-img">
                                <img src="{{asset('assets/img/man.jpg')}}">
                            </div>
                            <div class="blog-des">
                                <div class="blog-txt">
                                    @lang('lang.simply')
                                </div>
                                <div class="blog-dta star">
                                    <span class="date"><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i></span>
                                </div>
                            </div>
                        </div>
                        <div class="blog">
                            <div class="blog-img">
                                <img src="{{asset('assets/img/man.jpg')}}">
                            </div>
                            <div class="blog-des">
                                <div class="blog-txt">
                                    @lang('lang.simply')
                                </div>
                                <div class="blog-dta star">
                                    <span class="date"><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i></span>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>

            </div>
        </div>
</section>
<section class="slider-section bg-dark-sec">
    <div id="carouselExampleControls1" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{{asset('assets/img/slider1.jpg')}}">
                <div class="carousel-caption">
                    <h1> @lang('lang.third_slide_label')</h1>
                    <p>@lang('lang.cursus')</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{{asset('assets/img/slider2.jpg')}}">
                <div class="carousel-caption">
                    <h1> @lang('lang.third_slide_label')</h1>
                    <p>@lang('lang.cursus')</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{{asset('assets/img/slider3.jpg')}}">
                <div class="carousel-caption">
                    <h1> @lang('lang.third_slide_label')</h1>
                    <p>@lang('lang.cursus')</p>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls1" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">@lang('lang.previous')</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls1" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">@lang('lang.next')</span>
        </a>
    </div>
    </div>
</section>
<!-- Modal -->
<div class="modal fade" id="cancleBooking" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <section class="header-filter">
                    <div class="form-section">
                        <div class="form-all">
                            <div class="row mar-0">
                                <div class="col-12 pad-0">
                                    <h1 class="title">@lang('lang.are_you_sure?')</h1>
                                </div>
                                <div class="col-12 pad-0">
                                    <div class="form-group btn-area">
                                        <button class="p-btn btn btn-info" type="button" onclick="$('#cancleBooking').modal('hide');">
                                            @lang('lang.no')
                                        </button>
                                        <a href="" class="cancle-booking-url">
                                            <button class="p-btn btn btn-danger" type="button">
                                                @lang('lang.yes')
                                            </button>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
<script src="{{ asset('assets/DataTables/js/jquery.dataTables.min.js')}}"></script>
<script>
    window.base_url = "<?= url('/') ?>";
    window.cancle_book = "<?= url('user/cancle-booking') ?>";
</script>
<script>
    $(function() {
        $('#bookingListTable').DataTable();
    });
</script>
@endsection

appdata/resources/views/pages/live-zone-old.blade.php
@extends('layout.app')
@section('title')
Live Zone | GrožioKalviai
@endsection
@section('style')
<link rel="stylesheet" type="text/css" href="{{ asset('assets/css/fancybox.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('assets/css/cropper.css') }}">
{{-- <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/app.css') }}"> --}}
<style type="text/css">
  .date a {
    color: #E25B37;
  }

  .url-color {
    color: #E25B37;
  }

  #live-zone-textarea {
    border: none;
    background: black;
    margin-top: 9px;
  }

  .add-live-zone {
    margin-bottom: 10px;
    cursor: pointer;
  }

  .add_a_img {
    color: #2a9e63;
    text-decoration: underline;
    margin-right: 10px;
  }

  .embade_video {
    color: #E25B37;
    text-decoration: underline;
    margin-right: 10px;
  }

  #link-area,
  #img-area {
    display: none;
  }

  .imgVideo {
    display: none;
  }

  .imgVideoBlock {
    display: block;
  }

  .user-d img {
    height: 53px;
  }

  .user-d-img {
    float: left;
  }

  .user-d-d p {
    margin-left: 66px;
    margin-bottom: 0px;
    font-size: 18px;
  }

  .live-tlt h1 {
    font-size: 21px;
    margin-top: 33px;
  }

  .userPro-section .live-zona .live-zona-cnt .single-content {
    margin-bottom: 30px;
  }

  .userPro-section .live-zona .live-zona-cnt .single-content {
    background-color: none !important;
  }

  .sml-sp {
    font-size: 12px;
  }
</style>
@endsection
@section('content')
@include('inc.header-filter-new')
<section class="about-section userPro-section">
  <div class="max-fix-width">
    <div class="row mar-0">
      <div class="col-12 col-lg-7">
        @if(Auth::check())
        <div class="row">
          <div class="col-md-2">
            <img src="{{asset('assets/img/services/'.@$data['user']->profile_image)}}" class="rounded-circle img-fluid">
          </div>
          <div class="col-md-10">
            <div class="form-group">
              <textarea class="form-control" id="live-zone-textarea" rows="3" placeholder="Add live zone...." onclick="openLiveZone1()"></textarea>
            </div>
          </div>
        </div>
        @endif
        {{-- live zone add --}}



        <div class="live-zona">
          {{-- <div class="section-title">@lang('lang.live_zona')</div> --}}
          <div class="live-zona-cnt add-new-live-zone">
            @if(count($data['liveZones'])>0)
            @foreach ($data['liveZones'] as $liveZone)
            <div class="single-content">
              <div class="user-d">
                <div class="user-d-img">
                  @if($liveZone->user)
                  <img src="{{asset('userImage/fixPic/'.$liveZone->user->profile_image)}}" class="rounded-circle img-fluid">
                  @else
                  <img src="{{asset('userImage/fixPic/demo.jpg')}}" class="rounded-circle img-fluid">
                  @endif
                </div>
                <div class="user-d-d">
                  <p>
                    @if($liveZone->user)
                    {{$liveZone->user->name}} @if($liveZone->user->surname) {{$liveZone->user->surname}} @endif @if($liveZone->user->nickname) ({{$liveZone->user->surname}}) @endif
                    @endif
                  </p>
                  <p><span class="sml-sp">{{date('M d H:i a',strtotime($liveZone->created_at))}} {{ $liveZone->created_at->diffForHumans()}}</span></p>
                </div>
              </div>
              <div class="live-tlt">
                <h1>{{$liveZone->title}}</h1>
              </div>
              <div class="live-des">
                <p>{{$liveZone->description}}</p>
              </div>
              @if($liveZone->status == 1)
              <div class="content-img-p">
                <div class="content-img">
                  <img src="{{asset('liveZone/'.$liveZone->image)}}">
                </div>
              </div>
              @endif
              @if($liveZone->status == 2)
              <div class="content-img-p video">
                <div class="content-img">
                  <iframe src="{{$liveZone->image}}">
                  </iframe>
                </div>
              </div>
              @endif
            </div>
            @endforeach
            @endif

          </div>
        </div>
      </div>
      <div class="col-12 col-lg-5">
        <div class="side-blog">
          <section class="blog-section">
            <div id="vip-profile"></div>

          </section>
        </div>

        <div id="vip-services"></div>



      </div>
    </div>
  </div>
</section>
<section class="slider-section">
  <div class="max-fix-width">
    <div id="carouselExampleControls1" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{{asset('assets/img/slider1.jpg')}}">
          <div class="carousel-caption">
            <h1>@lang('lang.third_slider_lavel')</h1>
            <p>@lang('lang.praesent_commodo_cursus_magna_vel scelerisque_nisl_consectetur')</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="{{asset('assets/img/slider2.jpg')}}">
          <div class="carousel-caption">
            <h1>@lang('lang.third_slider_lavel')</h1>
            <p>@lang('lang.praesent_commodo_cursus_magna_vel scelerisque_nisl_consectetur')</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="{{asset('assets/img/slider3.jpg')}}">
          <div class="carousel-caption">
            <h1>@lang('lang.third_slider_lavel')</h1>
            <p>@lang('lang.praesent_commodo_cursus_magna_vel scelerisque_nisl_consectetur')</p>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleControls1" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">@lang('lang.previous')</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleControls1" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">@lang('lang.next')</span>
      </a>
    </div>
  </div>
</section>


{{-- live zone modal --}}
<form action="{{url('user/add-live-zone')}}" id="live_zone_form" method="POST" enctype="multipart/form-data" onsubmit="return addUpdateLiveZone()">
  @csrf
  <div class="modal fade cr-modal" id="liveZoneModal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true" style="z-index: 9999999">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">@lang('lang.add_live_zone')</h4>
        </div>
        <div class="modal-body" style="width: 100%; overflow: hidden;">
          <div class="col-12 pad-0">
            <div class="form-group">
              <label for="name">@lang('lang.title')</label>
              <input type="text" id="live_zone_title" class="form-control" placeholder="Title" aria-label="name" name="live_zone_title" required>
            </div>
          </div>
          <input type="hidden" name="live_zone_status" id="live_zone_status" value="">
          <input type="hidden" name="live_zone_id" id="live_zone_id" value="">
          <div class="col-12 pad-0">
            <div class="form-group">
              <label for="bio">@lang('lang.description')</label>
              <textarea id="live_zone_des" class="form-control" placeholder="Live zone description" name="live_zone_des"></textarea>
            </div>
          </div>
          <div class="col-12 pad-0">
            <div class="form-group">
              <label for="bio"><a href="javascript:;" class="add_a_img" onclick="imgEmbadeHideShow(1)">@lang('lang.update')</a></label>
              <label for="bio"><a href="javascript:;" class="embade_video" onclick="imgEmbadeHideShow(2)">@lang('lang.embade_a_video')</a></label>
            </div>
          </div>
          <div class="col-12 pad-0" id="link-area">
            <div class="form-group">
              <label for="name">@lang('lang.embade_link')</label>
              <input type="text" id="live_zone_vido_link" class="form-control" placeholder="Embade Video Link" aria-label="name" name="live_zone_vido_link">
            </div>
          </div>
          <div class="col-12 pad-0" id="img-area">
            <div class="form-group">
              <label for="name">@lang('lang.upload_image')</label>
              <input type="file" class="form-control-file" id="live_zone_img" name="live_zone_img">
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn" data-dismiss="modal">@lang('lang.cancel')</button>
          <button type="submit" class="btn" id="c_crop">@lang('lang.save')</button>
        </div>
      </div>
    </div>
  </div>
</form>
{{-- end live zone modal --}}




@endsection
@section('script')
<script src="{{ asset('assets/js/jquery.fancybox.js')}}"></script>
<script src="{{ asset('assets/js/cropper.js')}}"></script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places&key=AIzaSyAnMJd489Qa_hRJXPon9VFHHFpGchq8Ib4"></script>
<script>
  $(document).ready(function() {
    if ("geolocation" in navigator) {
      navigator.geolocation.getCurrentPosition(function(position) {
        lat = position.coords.latitude;
        lng = position.coords.longitude;
        getServiceAndProfile(lat, lng);
      }, function() {

      });
    }
  });

  function getServiceAndProfile(lat, lng) {
    var data = new FormData();
    data.append('lat', lat);
    data.append('lng', lng);
    data.append('_token', "{{csrf_token()}}");
    $.ajax({
      processData: false,
      contentType: false,
      data: data,
      type: 'POST',
      url: '{{url("get-profile-and-service")}}',
      success: function(response) {
        $('#vip-profile').html(response.profiles);
        $('#vip-services').html(response.services);
      }

    });
  }
</script>

<script>
  window.gallery_up = '<?= route('user.galleryFileUp') ?>';
  window.gallery_remove = '<?= route('user.galleryRemover') ?>';
  window.cover_pic_remove = '<?= route('user.userCoverRemover') ?>';
  window.profile_single_tmp_img = '<?= url("user/process-single-tmp-image") ?>';
  window.profile_single_tmp_remove = '<?= url("user/single-tmp-img-remove") ?>';
  window.cover_img_upload = '<?= url("user/cover-image-upload") ?>';
  window.get_profile_info = '<?= url("user/get-profile-information") ?>';
  window.insert_profile_info = '<?= url("user/insert-profile-information") ?>';


  $(function() {
    $('[data-fancybox="gallery"]').fancybox({
      thumbs: {
        autoStart: true
      }
    });
  });
</script>

<script>
  function openLiveZone1() {
    $('#live_zone_status').val('');
    $('#live_zone_title').val('');
    $('#live_zone_des').val('');
    $('#live_zone_id').val('');
    $('#live_zone_vido_link').val('');
    $('#live_zone_img').val('');
    $('#live_zone_form').attr('action', "{{url('user/add-live-zone')}}");
    $('#link-area').hide();
    $('#img-area').hide();
    $('#live_zone_status').val('');
    $('#liveZoneModal').modal('show');

  }
</script>
<script>
  function imgEmbadeHideShow(number) {
    if (number == 1) {
      $('#link-area').hide();
      $('#img-area').show();
      $('#live_zone_status').val(1);
    } else if (number == 2) {
      $('#link-area').show();
      $('#img-area').hide();
      $('#live_zone_status').val(2);
    }
  }
</script>


<script type="text/javascript">
  var page = 1;
  $(window).scroll(function() {
    // var scroll_height = $(window).scrollTop();
    // var window_height = $(window).height();
    // var document_height = $(document).height();
    // var scroll_height1 = scroll_height+window_height;
    // console.log('Scroll height='+scroll_height1);
    // console.log('Total Height='+document_height);
    // return false;
    if ($(window).scrollTop() + $(window).height() >= $(document).height() - 700) {
      page++;
      console.log('rasel');
      loadMoreData(page);
    }
  });

  function loadMoreData(page) {
    $.ajax({
        url: '?page=' + page,
        type: "get",
        beforeSend: function() {
          // $('.ajax-load').show();
        }
      })
      .done(function(data) {

        if (data.html == " ") {
          $('.ajax-load').html("No more records found");
          return;
        }
        // $('.ajax-load').hide();
        $(".add-new-live-zone").append(data.html);
      })
      .fail(function(jqXHR, ajaxOptions, thrownError) {

      });
  }
</script>


@endsection